# Generated by Django 2.1.4 on 2018-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181220_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_copy',
            field=models.BooleanField(default='False'),
        ),
    ]
